_target_: sah.algorithms.gather_activations_grammar.GrammarActivationCollector
grammar_config:
  _target_: sah.algorithms.utils.GrammarConfig
  base_path: /network/scratch/b/brownet/synthetic-data/subgrammar
tokenizer_config:
  _target_: sah.algorithms.utils.TokenizerConfig
  out_path: /network/scratch/b/brownet/synthetic-data/grammar/tokenizer.pkl
checkpoint_config:
  _target_: sah.algorithms.gather_activations_grammar.CheckpointConfig
  path: /network/scratch/b/brownet/hydra-runs/grammar/checkpoints/epoch_000_step_02600
