_target_: sah.algorithms.estimate_entropy.EntropyEstimator
activations_config:
  _target_: sah.algorithms.estimate_entropy.ActivationsConfig
  _recursive_: false
  _convert_: object
  activations_path: ${hydra:runtime.output_dir}/HuggingFaceTB/SmolLM2-360M-intermediate-checkpoints
  # input_activations: step_00050
  input_activations: step_00050
  output_activations: step-1280000
  layers: [10]
transformer_config:
  _target_: sah.algorithms.estimate_entropy.TransformerConfig
  _recursive_: false
  _convert_: object
  embed_dim: 960
  num_heads: 4
  hidden_dim: 2000
  num_layers: 2
