_target_: sah.algorithms.finetune_with_strategy.FinetuneWithStrategy
tokenizer_config:
  _target_: sah.algorithms.utils.data_classes.TokenizerConfig
  _recursive_: false
  _convert_: object
  use_fast: true
  trust_remote_code: true
model_config:
  _target_: sah.algorithms.utils.data_classes.NetworkConfig
  _recursive_: false
  _convert_: object
defaults:
  - strategy: iterative
  - model: qwen
  - dataset: metamath
result_file: ${hydra:runtime.output_dir}/results.csv
generations_dir: ${hydra:runtime.output_dir}/generations
seed: ${seed}
