_target_: sah.algorithms.train_with_strategy.TrainWithStrategy
finetuning_config:
  _target_: sah.algorithms.train_with_strategy.GrammarConfig
  base_path: /network/scratch/b/brownet/synthetic-data/base-automata
  size: 128
tokenizer_config:
  _target_: sah.algorithms.train_with_strategy.TokenizerConfig
  out_path: /network/scratch/b/brownet/synthetic-data/base-automata/tokenizer.pkl
transformer_config:
  _target_: sah.algorithms.networks.transformer.TransformerConfig
  d_model: 50
  dim_feedforward: 200
  n_heads: 5
  n_layers: 5
general_config:
  _target_: sah.algorithms.train_with_strategy.GeneralConfig
  data_variants_path: /network/scratch/b/brownet/synthetic-data/automata-repeated-variation
  pretraining_budget: 4096
  strategy: proposed
  tau: 0.01
  alpha: 1.5
  result_file: ${hydra:runtime.output_dir}/entropies.csv
