_target_: sah.algorithms.train_grammar_model.GrammarTrainer
grammar_config:
  _target_: sah.algorithms.train_grammar_model.GrammarConfig
  base_path: /network/scratch/b/brownet/synthetic-data/grammar
tokenizer_config:
  _target_: sah.algorithms.train_grammar_model.TokenizerConfig
  out_path: /network/scratch/b/brownet/synthetic-data/grammar/tokenizer.pkl
transformer_config:
  _target_: sah.algorithms.networks.transformer.TransformerConfig
  d_model: 50
  dim_feedforward: 200
  n_heads: 5
  n_layers: 5
