import json
import re

"""
This module contains functions to verify constraints in the responses generated by the model.
It covers all 25 constraints from the IFEval taxonomy. To be used either for eval or for ground truth rewards.
"""

def verify_keywords(text, keyword_list):
    """Verify if the response contains all the specified keywords."""
    response_lower = text.lower()
    return all(keyword.lower() in response_lower for keyword in keyword_list)

def verify_keyword_frequency(text, word, N):
    """Verifies if a keyword appears exactly N times in the given text."""
    text = text.lower()
    keyword = word.lower()
    import re
    words = re.findall(r'\b\w+\b', text)
    actual_count = sum(1 for word in words if word == keyword)
    constraint_met = actual_count == N
    return constraint_met

def validate_forbidden_words(text, forbidden_words):
    """Validates that the text does not contain any forbidden words."""
    text_lower = text.lower()
    found_words = [word for word in forbidden_words if word.lower() in text_lower]
    return len(found_words) == 0

def verify_letter_frequency(text: str, letter: str, N: int) -> bool:
    """Verifies if a given letter appears exactly the specified number of times."""
    if len(letter) != 1:
        raise ValueError("Letter parameter must be a single character")
    actual_count = text.count(letter)
    return actual_count == N

def validate_response_language(text, language):
    """Validates that the entire response is in the specified language."""
    from langdetect import detect
    detected_language = detect(text)
    return detected_language == language

def verify_paragraph_count(text: str, N: int) -> bool:
    """Verifies that text contains expected number of paragraphs separated by '* * *'."""
    def clean_text(text: str) -> str:
        return '\n'.join(line.strip() for line in text.splitlines()).strip()

    text = clean_text(text)
    paragraphs = text.split('* * *')
    actual_count = len(paragraphs)
    valid_paragraphs = [p.strip() for p in paragraphs if p.strip()]
    if len(valid_paragraphs) != actual_count:
        return False
    return actual_count == N

def validate_word_constraint(text: str, N: int, quantifier: str) -> bool:
    """Validates if text meets specified word count constraints."""
    words = text.strip().split()
    actual_count = len(words)
    tolerance = max(round(N * 0.1), 1)

    if quantifier == "at least":
        return actual_count >= N
    elif quantifier == "at most":
        return actual_count <= N
    elif quantifier == "around":
        return abs(actual_count - N) <= tolerance
    else:
        return False

def verify_sentence_constraint(text: str, N: int, quantifier: str) -> bool:
    """Verifies if text contains expected number of sentences."""
    sentences = re.split(r'(?<!\w\.\w.)(?<![A-Z][a-z]\.)(?<=\.|\?)\s', text)
    actual_count = len(sentences)

    if quantifier == 'at least':
        return actual_count >= N
    elif quantifier == 'around':
        return abs(actual_count - N) <= 1
    elif quantifier == 'at most':
        return actual_count <= N
    else:
        return False

def validate_paragraphs(text, N, first_word, i):
    """Validates paragraph count and first word of i-th paragraph."""
    paragraphs = text.split('\n\n')
    if len(paragraphs) != N:
        return False
    if paragraphs[i - 1].strip().startswith(first_word):
        return True
    return False

def verify_postscript(text, postscript_marker):
    """Verifies if text contains a postscript starting with marker."""
    if postscript_marker in text:
        marker_index = text.find(postscript_marker)
        remaining_text = text[marker_index:].strip()
        return len(remaining_text) > len(postscript_marker)
    return False

def validate_placeholders(text: str, N: int) -> tuple[bool, list[str]]:
    """Validates if text contains at least N placeholders in square brackets."""
    pattern = r'\[(.*?)\]'
    placeholders = re.findall(pattern, text)
    has_enough = len(placeholders) >= N
    return has_enough, placeholders

def verify_bullet_points(text: str, N: int) -> tuple[bool, str]:
    """Verifies if text contains exactly N markdown bullet points."""
    lines = text.split('\n')
    bullet_points = [line.strip() for line in lines if line.strip().startswith(('*', '-'))]
    actual_count = len(bullet_points)
    return actual_count == N

def validate_title(text: str) -> bool:
    """Validates if text contains a title wrapped in double angular brackets."""
    pattern = r"<<(.*?)>>"
    matches = re.findall(pattern, text)
    return len(matches) > 0

def validate_choice(text: str, options: list) -> bool:
    """Validates if text matches one of provided options."""
    for option in options:
        if text in option:
            return True
    return False

def validate_highlighted_sections(text: str, N: int) -> bool:
    """Validates at least N sections highlighted with asterisks."""
    pattern = r"\*(.*?)\*"
    matches = re.findall(pattern, text)
    return len(matches) >= N

def validate_sections(text: str, N: int, section_splitter: str) -> bool:
    """Validates text has N sections marked by section splitter."""
    sections = text.split(section_splitter)
    if sections[0] == '':
        sections.pop(0)
    return len(sections) == N

def validate_json_format(text: str) -> bool:
    """Validates if entire output is wrapped in JSON format."""
    try:
        json.loads(text)
    except ValueError:
        return False
    return True

def validate_repeat_prompt(text: str, original_prompt: str) -> bool:
    """Validates if text begins with repeated original prompt."""
    return text.startswith(original_prompt)

def validate_two_responses(text: str) -> bool:
    """Validates if text contains two different responses separated by six asterisks."""
    if text.count('******') == 1:
        response_list = text.split('******')
        first_response = response_list[0].strip()
        second_response = response_list[1].strip()
        if first_response != second_response:
            return True
    return False

def validate_uppercase(text: str) -> bool:
    """Validates if entire response is in capital letters."""
    return text == text.upper()

def validate_lowercase(text: str) -> bool:
    """Validates if entire response is in lowercase letters."""
    return text == text.lower()

def validate_frequency_capital_words(text: str, N: int, quantifier: str) -> bool:
    """Validates frequency of all-capital words."""
    words = re.findall(r'\b[A-Z]+\b', text)
    if quantifier == 'at least':
        return len(words) >= N
    elif quantifier == 'around':
        return len(words) == N
    elif quantifier == 'at most':
        return len(words) <= N
    else:
        return False

def validate_end(text: str, end_phrase: str) -> bool:
    """Validates if response ends with exact phrase."""
    return text.endswith(end_phrase)

def validate_quotation(text: str) -> bool:
    """Validates if entire response is wrapped in double quotation marks."""
    return text.startswith('"') and text.endswith('"')

def validate_no_commas(text: str) -> bool:
    """Validates that response contains no commas."""
    return ',' not in text
