defaults:
  - callbacks: default.yaml
  - logger: wandb
_target_: lightning.Trainer
accelerator: auto
strategy:
  _target_: lightning.pytorch.strategies.FSDPStrategy
  sharding_strategy: "FULL_SHARD"
devices: auto

deterministic: false

fast_dev_run: false

min_epochs: 1
max_epochs: 10

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like checkpoints and metrics
default_root_dir: ${hydra:runtime.output_dir}

detect_anomaly: false

limit_val_batches: 1
num_sanity_val_steps: 0
val_check_interval: 50
enable_checkpointing: true
