# @package _global_

algorithm:
  model_name: olmo3-7b-instruct-step200
  tokenizer_config:
    pretrained_model_name_or_path: allenai/Olmo-3-7B-Instruct
    revision: step_200
  model_config:
    pretrained_model_name_or_path: allenai/Olmo-3-7B-Instruct
    revision: step_200
    torch_dtype: bfloat16
