# @package _global_

algorithm:
  model_name: smollm3-stage2
  tokenizer_config:
    pretrained_model_name_or_path: HuggingFaceTB/SmolLM3-3B
    revision: null
  model_config:
    pretrained_model_name_or_path: HuggingFaceTB/SmolLM3-3B-checkpoints
    revision: stage2-step-4200000
