# @package _global_

algorithm:
  model_name: smollm3-step40k
  tokenizer_config:
    pretrained_model_name_or_path: HuggingFaceTB/SmolLM3-3B
  model_config:
    pretrained_model_name_or_path: HuggingFaceTB/SmolLM3-3B-checkpoints
    revision: stage1-step-40000
