_target_: sah.algorithms.strategies.phase_one.PhaseOneStrategy
_recursive_: false
_convert_: object
lr: 1e-5
r: 8
lora_alpha: 8
lora_dropout: 0.0
diffs_file: ${hydra:runtime.output_dir}/diffs_${algorithm.model_name}_${algorithm.dataset_name}
